export const mockdata = [
  {
    id: 1,
    name: "Crystal Jade Palace Lê Lợi",
    address: "123 Đường Lê Lợi, Quận 1, TP. Hồ Chí Minh",
    cuisine: "Việt Nam",
    cuisineIcon: "fas fa-utensils",
    status: "Mở cửa",
    priceRange: "150.000 - 400.000 VNĐ/người",
    capacity: 80,
    description: "Nhà hàng Việt Nam với không gian ấm cúng, phục vụ phở và bún chả truyền thống.",
    openingHours: "10:00 - 22:00",
    openTime: "10:00",
    closeTime: "22:00",
    rating: 4.5,
    reviewCount: 120,
    image: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg",
    mainImage: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg" },
      { image_url: "https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg" },
      { image_url: "https://images.pexels.com/photos/169523/pexels-photo-169523.jpeg" },
    ],
    location: { latitude: 10.7769, longitude: 106.7009 },
    contact: { phone: "028 1234 5678" },
    rules: [
      "Không mang đồ ăn từ ngoài vào.",
      "Hủy bàn trước 2 giờ nếu không sẽ mất cọc.",
      "Không hút thuốc trong nhà hàng.",
    ],
    paymentMethods: "Visa, MasterCard, Hỗ trợ VAT, MoMo",
    paymentMethodsIcon: "fas fa-credit-card",
    notSupported: "Thanh toán tiền mặt, Chỗ để xe máy",
    amenities: {
      wifi: true,
      parking: false,
      outdoorSeating: false,
      liveMusic: false,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-wifi",
    promotions: [
      {
        title: "Giảm 10% cho đặt bàn",
        description: "Áp dụng cho đặt bàn trước 24h",
        discount: 10,
        validUntil: "2025-06-30",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 50k",
        description: "Giảm 50.000 VNĐ cho hóa đơn từ 300k",
        discount: 0,
        validUntil: "2025-07-15",
        price: "50.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Phở Bò", price: "120.000 VNĐ", image: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg" },
      { name: "Bún Chả", price: "100.000 VNĐ", image: "https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg" },
    ],
    reviews: [
      { username: "Nguyen Van A", rating: 4.5, date: "2025-05-16", comment: "Ngon lắm!" },
      { username: "Tran Thi B", rating: 4.6, date: "2025-05-15", comment: "Không gian đẹp." },
    ],
    similarRestaurants: [
      { id: 2, name: "Nhà hàng Hải Sản Xanh", image: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg", cuisine: "Hải sản", rating: 4.2 },
    ],
    booking: {
      minPeople: 1,
      maxPeople: 10,
      availableTimes: ["10:00", "12:00", "18:00"],
      deposit: 5000,
    },
    distance: 1.5,
    createdAt: "2025-05-15T03:30:00.000Z",
    updatedAt: "2025-05-15T04:00:00.000Z",
    category: "all",
    discount: "Đặt bàn giảm giá",
    suitableFor: "Gia đình, Bạn bè, Cặp đôi",
    signatureDish: "Phở Bò Tái",
    ambiance: "Ấm cúng, Truyền thống",
    parking: "Có bãi đỗ xe máy",
    parkingDetails: "Có bãi đỗ xe máy miễn phí cho khách, nhưng không có chỗ để xe ô tô.",
    highlight: "Không gian mang đậm nét văn hóa Việt Nam, phục vụ món ăn truyền thống chuẩn vị.",
    operatingHours: [
      { day: "Thứ Hai", time: "10:00 - 22:00" },
      { day: "Thứ Ba", time: "10:00 - 22:00" },
      { day: "Thứ Tư", time: "10:00 - 22:00" },
      { day: "Thứ Năm", time: "10:00 - 22:00" },
      { day: "Thứ Sáu", time: "10:00 - 22:00" },
      { day: "Thứ Bảy", time: "10:00 - 22:00" },
      { day: "Chủ Nhật", time: "10:00 - 22:00" },
    ],
    introduction: "Nhà hàng Mẫu Việt Nam mang đến trải nghiệm ẩm thực đậm chất Việt với không gian truyền thống, ấm cúng. Chúng tôi tự hào phục vụ các món ăn đặc trưng như phở bò, bún chả, và gỏi cuốn, tất cả đều được chế biến từ nguyên liệu tươi ngon nhất.",
    detailImages: [
      "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg",
      "https://images.pexels.com/photos/1410235/pexels-photo-1410235.jpeg",
    ],
  },
  {
    id: 2,
    name: "Nhà hàng Hải Sản Xanh",
    address: "45 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh",
    cuisine: "Hải sản",
    cuisineIcon: "fas fa-fish",
    status: "Mở cửa",
    priceRange: "200.000 - 500.000 VNĐ/người",
    capacity: 60,
    description: "Chuyên hải sản tươi sống, không gian sang trọng.",
    openingHours: "11:00 - 23:00",
    openTime: "11:00",
    closeTime: "23:00",
    rating: 4.2,
    reviewCount: 85,
    image: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg",
    mainImage: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg" },
      { image_url: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg" },
      { image_url: "https://images.pexels.com/photos/3153192/pexels-photo-3153192.jpeg" },
    ],
    location: { latitude: 10.7760, longitude: 106.7032 },
    contact: { phone: "028 5678 1234" },
    rules: [
      "Đặt cọc 50% cho nhóm trên 5 người.",
      "Hủy bàn trước 4 giờ nếu không sẽ mất cọc.",
      "Không mang thú cưng vào nhà hàng.",
    ],
    paymentMethods: "Visa, MasterCard, ZaloPay",
    paymentMethodsIcon: "fas fa-credit-card",
    notSupported: "Chỗ để xe ô tô",
    amenities: {
      wifi: true,
      parking: true,
      outdoorSeating: false,
      liveMusic: false,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-parking",
    promotions: [
      {
        title: "Giảm 15% cho nhóm",
        description: "Áp dụng cho nhóm từ 5 người trở lên",
        discount: 15,
        validUntil: "2025-07-01",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 100k",
        description: "Giảm 100.000 VNĐ cho hóa đơn từ 500k",
        discount: 0,
        validUntil: "2025-07-20",
        price: "100.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Cua Hấp Bia", price: "300.000 VNĐ", image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg" },
      { name: "Tôm Hùm Nướng", price: "500.000 VNĐ", image: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg" },
    ],
    reviews: [
      { username: "Le Thi C", rating: 4.0, date: "2025-05-14", comment: "Tươi ngon!" },
      { username: "Pham Van D", rating: 4.3, date: "2025-05-13", comment: "Dịch vụ tốt." },
    ],
    similarRestaurants: [
      { id: 1, name: "Crystal Jade Palace Lê Lợi", image: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg", cuisine: "Việt Nam", rating: 4.5 },
    ],
    booking: {
      minPeople: 1,
      maxPeople: 8,
      availableTimes: ["11:00", "19:00"],
      deposit: 5000,
    },
    distance: 0.8,
    createdAt: "2025-05-14T12:00:00.000Z",
    updatedAt: "2025-05-14T12:30:00.000Z",
    category: "seafoodRestaurants",
    discount: null,
    suitableFor: "Gia đình, Tụ họp nhóm, Khách du lịch",
    signatureDish: "Cua Hấp Bia",
    ambiance: "Sang trọng, Hiện đại",
    parking: "Có bãi đỗ xe máy",
    parkingDetails: "Có bãi đỗ xe máy cho khách, nhưng không có chỗ để xe ô tô do không gian hạn chế.",
    highlight: "Hải sản tươi sống được nhập trực tiếp từ ngư dân, không gian sang trọng phù hợp cho các buổi tiệc.",
    operatingHours: [
      { day: "Thứ Hai", time: "11:00 - 23:00" },
      { day: "Thứ Ba", time: "11:00 - 23:00" },
      { day: "Thứ Tư", time: "11:00 - 23:00" },
      { day: "Thứ Năm", time: "11:00 - 23:00" },
      { day: "Thứ Sáu", time: "11:00 - 23:00" },
      { day: "Thứ Bảy", time: "11:00 - 23:00" },
      { day: "Chủ Nhật", time: "11:00 - 23:00" },
    ],
    introduction: "Nhà hàng Hải Sản Xanh là điểm đến lý tưởng cho những ai yêu thích hải sản tươi sống. Với không gian hiện đại và sang trọng, chúng tôi mang đến những món ăn hấp dẫn như cua hấp bia, tôm hùm nướng, và ghẹ rang me.",
    detailImages: [
      "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg",
      "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
    ],
  },
  {
    id: 3,
    name: "Nhà hàng Trung Hoa Phượng Hoàng",
    address: "78 Đường Nguyễn Trãi, Quận 5, TP. Hồ Chí Minh",
    cuisine: "Trung Hoa",
    cuisineIcon: "fas fa-dragon",
    status: "Mở cửa",
    priceRange: "180.000 - 450.000 VNĐ/người",
    capacity: 100,
    description: "Nhà hàng Trung Hoa với các món dimsum và vịt quay Bắc Kinh nổi tiếng.",
    openingHours: "09:00 - 21:00",
    openTime: "09:00",
    closeTime: "21:00",
    rating: 4.7,
    reviewCount: 150,
    image: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg",
    mainImage: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg" },
      { image_url: "https://images.pexels.com/photos/723240/pexels-photo-723240.jpeg" },
      { image_url: "https://images.pexels.com/photos/723247/pexels-photo-723247.jpeg" },
    ],
    location: { latitude: 10.7592, longitude: 106.6823 },
    contact: { phone: "028 9876 5432" },
    rules: [
      "Không mang đồ uống từ ngoài vào.",
      "Hủy bàn trước 3 giờ nếu không sẽ mất cọc.",
      "Không mang thú cưng vào nhà hàng.",
    ],
    paymentMethods: "Visa, MasterCard, Tiền mặt",
    paymentMethodsIcon: "fas fa-money-bill",
    notSupported: "Chỗ để xe ô tô, ZaloPay",
    amenities: {
      wifi: true,
      parking: false,
      outdoorSeating: true,
      liveMusic: false,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-chair",
    promotions: [
      {
        title: "Giảm 15% hóa đơn",
        description: "Áp dụng cho hóa đơn trên 1.000.000 VNĐ",
        discount: 15,
        validUntil: "2025-06-30",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 80k",
        description: "Giảm 80.000 VNĐ cho hóa đơn từ 400k",
        discount: 0,
        validUntil: "2025-07-10",
        price: "80.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Vịt Quay Bắc Kinh", price: "400.000 VNĐ", image: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg" },
      { name: "Dimsum Hấp", price: "150.000 VNĐ", image: "https://images.pexels.com/photos/723240/pexels-photo-723240.jpeg" },
    ],
    reviews: [
      { username: "Hoang Van E", rating: 4.8, date: "2025-05-12", comment: "Dimsum ngon tuyệt!" },
      { username: "Nguyen Thi F", rating: 4.6, date: "2025-05-11", comment: "Không gian rất Trung Hoa." },
    ],
    similarRestaurants: [
      { id: 1, name: "Crystal Jade Palace Lê Lợi", image: "https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg", cuisine: "Việt Nam", rating: 4.5 },
    ],
    booking: {
      minPeople: 2,
      maxPeople: 12,
      availableTimes: ["09:00", "13:00", "19:00"],
      deposit: 10000,
    },
    distance: 2.3,
    createdAt: "2025-05-13T09:00:00.000Z",
    updatedAt: "2025-05-13T09:30:00.000Z",
    category: "chineseRestaurants",
    discount: "Đặt bàn giảm giá",
    suitableFor: "Gia đình, Tụ họp nhóm",
    signatureDish: "Vịt Quay Bắc Kinh",
    ambiance: "Truyền thống Trung Hoa, Sang trọng",
    parking: "Không có bãi đỗ xe",
    parkingDetails: "Không có bãi đỗ xe, khách hàng có thể gửi xe ở khu vực lân cận.",
    highlight: "Món vịt quay Bắc Kinh chuẩn vị, không gian đậm chất Trung Hoa với đèn lồng đỏ.",
    operatingHours: [
      { day: "Thứ Hai", time: "09:00 - 21:00" },
      { day: "Thứ Ba", time: "09:00 - 21:00" },
      { day: "Thứ Tư", time: "09:00 - 21:00" },
      { day: "Thứ Năm", time: "09:00 - 21:00" },
      { day: "Thứ Sáu", time: "09:00 - 21:00" },
      { day: "Thứ Bảy", time: "09:00 - 21:00" },
      { day: "Chủ Nhật", time: "09:00 - 21:00" },
    ],
    introduction: "Nhà hàng Trung Hoa Phượng Hoàng mang đến hương vị Trung Hoa đích thực với các món ăn nổi tiếng như vịt quay Bắc Kinh và dimsum hấp. Không gian được trang trí đậm chất truyền thống với đèn lồng đỏ và nội thất gỗ tinh tế.",
    detailImages: [
      "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg",
      "https://images.pexels.com/photos/723240/pexels-photo-723240.jpeg",
    ],
  },
  {
    id: 4,
    name: "Nhà hàng Tiệc Sang Trọng",
    address: "56 Đường Trần Hưng Đạo, Quận 3, TP. Hồ Chí Minh",
    cuisine: "Quốc tế",
    cuisineIcon: "fas fa-globe",
    status: "Mở cửa",
    priceRange: "300.000 - 800.000 VNĐ/người",
    capacity: 120,
    description: "Nhà hàng cao cấp phục vụ các món ăn quốc tế, phù hợp cho tiệc cưới và sự kiện.",
    openingHours: "11:00 - 22:00",
    openTime: "11:00",
    closeTime: "22:00",
    rating: 4.9,
    reviewCount: 200,
    image: "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg",
    mainImage: "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg" },
      { image_url: "https://images.pexels.com/photos/704982/pexels-photo-704982.jpeg" },
      { image_url: "https://images.pexels.com/photos/3184183/pexels-photo-3184183.jpeg" },
    ],
    location: { latitude: 10.7800, longitude: 106.6900 },
    contact: { phone: "028 1111 2222" },
    rules: [
      "Đặt cọc 30% cho tiệc trên 20 người.",
      "Hủy bàn trước 48 giờ nếu không sẽ mất cọc.",
      "Trang phục lịch sự.",
    ],
    paymentMethods: "Visa, MasterCard, Chuyển khoản",
    paymentMethodsIcon: "fas fa-credit-card",
    notSupported: "Tiền mặt, MoMo",
    amenities: {
      wifi: true,
      parking: true,
      outdoorSeating: false,
      liveMusic: true,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-music",
    promotions: [
      {
        title: "Giảm 20% tiệc cưới",
        description: "Áp dụng cho tiệc cưới đặt trước 1 tháng",
        discount: 20,
        validUntil: "2025-12-31",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 150k",
        description: "Giảm 150.000 VNĐ cho hóa đơn từ 800k",
        discount: 0,
        validUntil: "2025-08-01",
        price: "150.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Bò Bít Tết", price: "450.000 VNĐ", image: "https://images.pexels.com/photos/704982/pexels-photo-704982.jpeg" },
      { name: "Cá Hồi Áp Chảo", price: "400.000 VNĐ", image: "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg" },
    ],
    reviews: [
      { username: "Tran Van G", rating: 5.0, date: "2025-05-10", comment: "Tuyệt vời cho tiệc cưới!" },
      { username: "Le Thi H", rating: 4.8, date: "2025-05-09", comment: "Đồ ăn ngon, phục vụ chuyên nghiệp." },
    ],
    similarRestaurants: [
      { id: 2, name: "Nhà hàng Hải Sản Xanh", image: "https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg", cuisine: "Hải sản", rating: 4.2 },
    ],
    booking: {
      minPeople: 10,
      maxPeople: 50,
      availableTimes: ["11:00", "18:00", "20:00"],
      deposit: 20000,
    },
    distance: 3.5,
    createdAt: "2025-05-12T10:00:00.000Z",
    updatedAt: "2025-05-12T10:30:00.000Z",
    category: "partyRestaurants",
    discount: "Đặt bàn giảm giá",
    suitableFor: "Tiệc cưới, Sự kiện, Tụ họp nhóm",
    signatureDish: "Bò Bít Tết Thượng Hạng",
    ambiance: "Sang trọng, Lãng mạn",
    parking: "Có bãi đỗ xe ô tô",
    parkingDetails: "Có bãi đỗ xe ô tô và xe máy miễn phí cho khách.",
    highlight: "Không gian sang trọng lý tưởng cho tiệc cưới và sự kiện, với thực đơn quốc tế đa dạng.",
    operatingHours: [
      { day: "Thứ Hai", time: "11:00 - 22:00" },
      { day: "Thứ Ba", time: "11:00 - 22:00" },
      { day: "Thứ Tư", time: "11:00 - 22:00" },
      { day: "Thứ Năm", time: "11:00 - 22:00" },
      { day: "Thứ Sáu", time: "11:00 - 22:00" },
      { day: "Thứ Bảy", time: "11:00 - 22:00" },
      { day: "Chủ Nhật", time: "11:00 - 22:00" },
    ],
    introduction: "Nhà hàng Tiệc Sang Trọng là lựa chọn hàng đầu cho các sự kiện lớn như tiệc cưới, hội nghị, và tiệc công ty. Với không gian lãng mạn, sang trọng và thực đơn quốc tế đa dạng, chúng tôi cam kết mang đến trải nghiệm đáng nhớ.",
    detailImages: [
      "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg",
      "https://images.pexels.com/photos/704982/pexels-photo-704982.jpeg",
    ],
  },
  {
    id: 5,
    name: "Nhà hàng Gợi Ý Ăn Trưa",
    address: "12 Đường Nguyễn Thị Minh Khai, Quận 1, TP. Hồ Chí Minh",
    cuisine: "Nhật Bản",
    cuisineIcon: "fas fa-sushi",
    status: "Mở cửa",
    priceRange: "100.000 - 300.000 VNĐ/người",
    capacity: 50,
    description: "Nhà hàng Nhật Bản phục vụ các món sushi và cơm trưa tiện lợi.",
    openingHours: "11:00 - 15:00",
    openTime: "11:00",
    closeTime: "15:00",
    rating: 4.3,
    reviewCount: 90,
    image: "https://images.pexels.com/photos/1352277/pexels-photo-1352277.jpeg",
    mainImage: "https://images.pexels.com/photos/1352277/pexels-photo-1352277.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/1352277/pexels-photo-1352277.jpeg" },
      { image_url: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg" },
      { image_url: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg" },
    ],
    location: { latitude: 10.7810, longitude: 106.6950 },
    contact: { phone: "028 3333 4444" },
    rules: [
      "Không mang đồ ăn từ ngoài vào.",
      "Không phục vụ sau 15:00.",
      "Không mang thú cưng.",
    ],
    paymentMethods: "Tiền mặt, MoMo",
    paymentMethodsIcon: "fas fa-money-bill",
    notSupported: "Visa, MasterCard, Chỗ để xe",
    amenities: {
      wifi: true,
      parking: false,
      outdoorSeating: false,
      liveMusic: false,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-wifi",
    promotions: [
      {
        title: "Giảm 10% bữa trưa",
        description: "Áp dụng cho hóa đơn từ 200k vào giờ trưa",
        discount: 10,
        validUntil: "2025-06-25",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 30k",
        description: "Giảm 30.000 VNĐ cho hóa đơn từ 150k",
        discount: 0,
        validUntil: "2025-07-05",
        price: "30.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Sushi Cá Hồi", price: "150.000 VNĐ", image: "https://images.pexels.com/photos/1352277/pexels-photo-1352277.jpeg" },
      { name: "Cơm Bento", price: "120.000 VNĐ", image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg" },
    ],
    reviews: [
      { username: "Nguyen Van I", rating: 4.2, date: "2025-05-08", comment: "Sushi rất tươi!" },
      { username: "Tran Thi K", rating: 4.4, date: "2025-05-07", comment: "Phù hợp cho bữa trưa." },
    ],
    similarRestaurants: [
      { id: 3, name: "Nhà hàng Trung Hoa Phượng Hoàng", image: "https://images.pexels.com/photos/723198/pexels-photo-723198.jpeg", cuisine: "Trung Hoa", rating: 4.7 },
    ],
    booking: {
      minPeople: 1,
      maxPeople: 6,
      availableTimes: ["11:00", "12:00", "14:00"],
      deposit: 0,
    },
    distance: 1.2,
    createdAt: "2025-05-11T11:00:00.000Z",
    updatedAt: "2025-05-11T11:30:00.000Z",
    category: "lunchSuggestions",
    discount: null,
    suitableFor: "Nhân viên văn phòng, Bạn bè",
    signatureDish: "Sushi Cá Hồi",
    ambiance: "Nhẹ nhàng, Hiện đại",
    parking: "Không có bãi đỗ xe",
    parkingDetails: "Không có bãi đỗ xe, khách hàng gửi xe ở khu vực gần đó.",
    highlight: "Thực đơn bữa trưa đa dạng, phù hợp cho dân văn phòng với không gian nhẹ nhàng, thoải mái.",
    operatingHours: [
      { day: "Thứ Hai", time: "11:00 - 15:00" },
      { day: "Thứ Ba", time: "11:00 - 15:00" },
      { day: "Thứ Tư", time: "11:00 - 15:00" },
      { day: "Thứ Năm", time: "11:00 - 15:00" },
      { day: "Thứ Sáu", time: "11:00 - 15:00" },
      { day: "Thứ Bảy", time: "Đóng cửa" },
      { day: "Chủ Nhật", time: "Đóng cửa" },
    ],
    introduction: "Nhà hàng Gợi Ý Ăn Trưa là điểm đến lý tưởng cho bữa trưa nhanh chóng và ngon miệng. Chúng tôi chuyên phục vụ các món Nhật như sushi, cơm bento, và sashimi với nguyên liệu tươi ngon, đảm bảo chất lượng.",
    detailImages: [
      "https://images.pexels.com/photos/1352277/pexels-photo-1352277.jpeg",
      "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
    ],
  },
  {
    id: 6,
    name: "Le Jardin - Nhà hàng Pháp Tinh Tế",
    address: "89 Đường Pasteur, Quận 1, TP. Hồ Chí Minh",
    cuisine: "Quốc tế",
    cuisineIcon: "fas fa-glass-cheers",
    status: "Mở cửa",
    priceRange: "400.000 - 1.000.000 VNĐ/người",
    capacity: 150,
    description: "Nhà hàng Pháp cao cấp với không gian sang trọng, phục vụ thực đơn tinh tế cùng rượu vang thượng hạng.",
    openingHours: "12:00 - 23:00",
    openTime: "12:00",
    closeTime: "23:00",
    rating: 4.8,
    reviewCount: 180,
    image: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg",
    mainImage: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg",
    images: [
      { image_url: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg" }, // Không gian Pháp
      { image_url: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg" }, // Món ăn Pháp
      { image_url: "https://images.pexels.com/photos/1410236/pexels-photo-1410236.jpeg" }, // View sang trọng
    ],
    location: { latitude: 10.7790, longitude: 106.6990 },
    contact: { phone: "028 9999 8888" },
    rules: [
      "Đặt cọc 20% cho tiệc trên 10 người.",
      "Hủy bàn trước 24 giờ nếu không sẽ mất cọc.",
      "Trang phục lịch sự bắt buộc.",
    ],
    paymentMethods: "Visa, MasterCard, Chuyển khoản",
    paymentMethodsIcon: "fas fa-credit-card",
    notSupported: "Tiền mặt",
    amenities: {
      wifi: true,
      parking: true,
      outdoorSeating: true,
      liveMusic: true,
      petFriendly: false,
      airConditioning: true,
    },
    amenitiesIcon: "fas fa-wine-glass",
    promotions: [
      {
        title: "Giảm 25% cho tiệc tối",
        description: "Áp dụng cho đặt tiệc tối từ 6 người trở lên",
        discount: 25,
        validUntil: "2025-08-31",
        price: "0 VNĐ",
        icon: "fas fa-tag",
      },
      {
        title: "Voucher 200k",
        description: "Giảm 200.000 VNĐ cho hóa đơn từ 1.000k",
        discount: 0,
        validUntil: "2025-09-15",
        price: "200.000 VNĐ",
        icon: "fas fa-tag",
      },
    ],
    menu: [
      { name: "Bò Bít Tết kiểu Pháp", price: "600.000 VNĐ", image: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg" },
      { name: "Súp Hào Tươi", price: "450.000 VNĐ", image: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg" },
    ],
    reviews: [
      { username: "Pham Thi L", rating: 4.9, date: "2025-05-10", comment: "Không gian tuyệt vời, đồ ăn ngon!" },
      { username: "Le Van M", rating: 4.7, date: "2025-05-09", comment: "Phù hợp cho tiệc sang trọng." },
    ],
    similarRestaurants: [
      { id: 4, name: "Nhà hàng Tiệc Sang Trọng", image: "https://images.pexels.com/photos/941861/pexels-photo-941861.jpeg", cuisine: "Quốc tế", rating: 4.9 },
    ],
    booking: {
      minPeople: 2,
      maxPeople: 60,
      availableTimes: ["12:00", "18:00", "20:00"],
      deposit: 20000,
    },
    distance: 2.0,
    createdAt: "2025-05-10T15:00:00.000Z",
    updatedAt: "2025-05-10T15:30:00.000Z",
    category: "luxuryRestaurants",
    discount: "Đặt bàn giảm giá",
    suitableFor: "Tiệc cưới, Sự kiện, Khách du lịch",
    signatureDish: "Bò Bít Tết kiểu Pháp",
    ambiance: "Sang trọng, Lãng mạn",
    parking: "Có bãi đỗ xe ô tô",
    parkingDetails: "Có bãi đỗ xe ô tô và xe máy miễn phí cho khách.",
    highlight: "Thực đơn Pháp tinh tế với rượu vang thượng hạng, view thành phố đẹp mắt.",
    operatingHours: [
      { day: "Thứ Hai", time: "12:00 - 23:00" },
      { day: "Thứ Ba", time: "12:00 - 23:00" },
      { day: "Thứ Tư", time: "12:00 - 23:00" },
      { day: "Thứ Năm", time: "12:00 - 23:00" },
      { day: "Thứ Sáu", time: "12:00 - 23:00" },
      { day: "Thứ Bảy", time: "12:00 - 23:00" },
      { day: "Chủ Nhật", time: "12:00 - 23:00" },
    ],
    introduction: "Le Jardin mang đến trải nghiệm ẩm thực Pháp đỉnh cao với không gian sang trọng và view panorama tuyệt đẹp. Thực đơn bao gồm các món ăn cao cấp như bò bít tết kiểu Pháp và súp hào tươi, kết hợp với bộ sưu tập rượu vang đa dạng.",
    detailImages: [
      "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg",
      "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg",
    ],
  },
];

export const useMockData = true;